name: ${project.name}
version: ${project.version}
author: [Endain]
main: org.dotGaming.Endain.CleverNotch.CleverNotch
commands:
   clevernotch:
      description: Toggle the CleverNotch plugin between ON and OFF!
      usage: /<command>